spring:
  datasource:
    driver-class-name: org.testcontainers.jdbc.ContainerDatabaseDriver
    url: jdbc:tc:postgresql:16:///fact
  cloud:
    azure:
      storage:
        # allows blob store autoconfigure to complete without exception
        account-name: test
  autoconfigure:
    exclude:
      - com.azure.spring.cloud.autoconfigure.implementation.context.AzureTokenCredentialAutoConfiguration

os:
  url: https://api.os.uk
  key: a-key
