spring:
  datasource:
    driver-class-name: org.testcontainers.jdbc.ContainerDatabaseDriver
    url: jdbc:tc:postgresql:16:///fact

migration:
  source-base-url: ${FACT_MIGRATION_SOURCE_BASE_URL:http://localhost:8080}

logging:
  level:
    uk.gov.hmcts.reform.fact.data.api.migration: DEBUG
