spring:
  datasource:
    driver-class-name: org.testcontainers.jdbc.ContainerDatabaseDriver
    url: jdbc:tc:postgresql:16:///fact

user:
  retention-period: 365

courtLock:
  timeout-minutes: 60

os:
  url: https://api.os.uk
  key: a-key

migration:
  source-base-url: ${FACT_MIGRATION_SOURCE_BASE_URL:http://localhost:8080}
